export enum LayerType {
    DRILLED_WELLBORE_PICKS = "DRILLED_WELLBORE_PICKS",
    DRILLED_WELL_TRAJECTORIES = "DRILLED_WELL_TRAJECTORIES",
    INTERSECTION_REALIZATION_GRID = "INTERSECTION_REALIZATION_GRID",
    INTERSECTION_REALIZATION_OBSERVED_SEISMIC = "INTERSECTION_REALIZATION_OBSERVED_SEISMIC",
    INTERSECTION_REALIZATION_SIMULATED_SEISMIC = "INTERSECTION_REALIZATION_SIMULATED_SEISMIC",
}
