export enum CustomDataProviderType {
    ENSEMBLE_WELLBORE_PICKS = "ENSEMBLE_WELLBORE_PICKS",
    REALIZATION_SURFACES = "REALIZATION_SURFACES",
    PER_REALIZATION_SURFACES = "PER_REALIZATION_SURFACES",
}
